- 데이터변환 및 재구성방법
- penguins 데이터를 활용해 데이터변환 및 재구성

- 학습내용
- 1. 범주형 데이터처리
- 2. 열재구성
- 3. 필터링

In [1]:
# 범주형데이터처리
# 구간분할(binding) : cut()함수를 이용하여, 경곗값을 지정해 구간분할
import seaborn as sns
df = sns.load_dataset('mpg')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    object 
 8   name          398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB


In [2]:
print(df['horsepower']) # 연속형데이터인 horsepower를 구간분할 할 예정

0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...  
393     86.0
394     52.0
395     84.0
396     79.0
397     82.0
Name: horsepower, Length: 398, dtype: float64


In [3]:
import pandas as pd
df['hp_bin']=pd.cut(df['horsepower'],
                   bins=[46,105,165,230],
                   labels=['저출력','보통출력','고출력'],
                   include_lowest=True)
print(df['hp_bin'])

0      보통출력
1      보통출력
2      보통출력
3      보통출력
4      보통출력
       ... 
393     저출력
394     저출력
395     저출력
396     저출력
397     저출력
Name: hp_bin, Length: 398, dtype: category
Categories (3, object): ['저출력' < '보통출력' < '고출력']


In [4]:
# histogram() : 구간수를 지정하여 구간 경곗값 확인
# 히스토그램 함수는 누락데이터가 존재하지 않을 때만 사용이 가능하다는 점 유의
import seaborn as sns
df = sns.load_dataset('mpg')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    object 
 8   name          398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB


In [5]:
df.dropna(subset=['horsepower'], axis=0, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 392 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64  
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        392 non-null    int64  
 5   acceleration  392 non-null    float64
 6   model_year    392 non-null    int64  
 7   origin        392 non-null    object 
 8   name          392 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 30.6+ KB


In [6]:
import numpy as np
np.histogram(df['horsepower'], bins=3)

(array([257, 103,  32], dtype=int64),
 array([ 46.        , 107.33333333, 168.66666667, 230.        ]))

In [7]:
count, bin_dividers = np.histogram(df['horsepower'], bins=3)
print(bin_dividers)

[ 46.         107.33333333 168.66666667 230.        ]


In [8]:
df['hp_bin'] = pd.cut(df['horsepower'],
                      bins=bin_dividers,
                      labels=['저출력','보통출력','고출력'],
                      include_lowest=True)
print(df['hp_bin'])

0      보통출력
1      보통출력
2      보통출력
3      보통출력
4      보통출력
       ... 
393     저출력
394     저출력
395     저출력
396     저출력
397     저출력
Name: hp_bin, Length: 392, dtype: category
Categories (3, object): ['저출력' < '보통출력' < '고출력']


In [9]:
# 범주형변수의 더미변수 변환 : 해당특성이 존재하면 1, 아니면 0으로 표현
# one-hot encoding 방법
# 축소 랭크 방법 : refrence coding

In [10]:
# get_dummies() : 범주형범주를 더미변수로 변환
horsepower_dummies = pd.get_dummies(df['hp_bin'])

In [11]:
print(horsepower_dummies)

     저출력  보통출력  고출력
0      0     1    0
1      0     1    0
2      0     1    0
3      0     1    0
4      0     1    0
..   ...   ...  ...
393    1     0    0
394    1     0    0
395    1     0    0
396    1     0    0
397    1     0    0

[392 rows x 3 columns]


In [12]:
# 축소랭크 방식으로 더미변수 생성
horsepower_dummies1 = pd.get_dummies(df['hp_bin'], drop_first=True)
print(horsepower_dummies1)
# 저출력을 기준값으로 2개로 축소됨

     보통출력  고출력
0       1    0
1       1    0
2       1    0
3       1    0
4       1    0
..    ...  ...
393     0    0
394     0    0
395     0    0
396     0    0
397     0    0

[392 rows x 2 columns]


In [13]:
# 열 재구성
import seaborn as sns
df = sns.load_dataset('mpg')
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [14]:
# 열순서 바꾸기
df1 = df[['mpg','name','horsepower','cylinders','model_year']]
print(df1)

      mpg                       name  horsepower  cylinders  model_year
0    18.0  chevrolet chevelle malibu       130.0          8          70
1    15.0          buick skylark 320       165.0          8          70
2    18.0         plymouth satellite       150.0          8          70
3    16.0              amc rebel sst       150.0          8          70
4    17.0                ford torino       140.0          8          70
..    ...                        ...         ...        ...         ...
393  27.0            ford mustang gl        86.0          4          82
394  44.0                  vw pickup        52.0          4          82
395  32.0              dodge rampage        84.0          4          82
396  28.0                ford ranger        79.0          4          82
397  31.0                 chevy s-10        82.0          4          82

[398 rows x 5 columns]


In [15]:
# 열순서 정렬
# reverse=False(오름차순정렬), True(내림차순정렬)
import seaborn as sns
df = sns.load_dataset('mpg')
list(df.columns)
list1 = sorted(list(df.columns))
df[list1]

acceleration  cylinders  displacement  horsepower  model_year   mpg  \
0            12.0          8         307.0       130.0          70  18.0   
1            11.5          8         350.0       165.0          70  15.0   
2            11.0          8         318.0       150.0          70  18.0   
3            12.0          8         304.0       150.0          70  16.0   
4            10.5          8         302.0       140.0          70  17.0   
..            ...        ...           ...         ...         ...   ...   
393          15.6          4         140.0        86.0          82  27.0   
394          24.6          4          97.0        52.0          82  44.0   
395          11.6          4         135.0        84.0          82  32.0   
396          18.6          4         120.0        79.0          82  28.0   
397          19.4          4         119.0        82.0          82  31.0   

                          name  origin  weight  
0    chevrolet chevelle malibu     usa    3504  
1            buick skylark 320     usa    3693  
2           plymouth satellite     usa    3436  
3                amc rebel sst     usa    3433  
4                  ford torino     usa    3449  
..                         ...     ...     ...  
393            ford mustang gl     usa    2790  
394                  vw pickup  europe    2130  
395              dodge rampage     usa    2295  
396                ford ranger     usa    2625  
397                 chevy s-10     usa    2720  

[398 rows x 9 columns]

In [16]:
import seaborn as sns
df = sns.load_dataset('mpg')
list(df.columns)
list2 = sorted(list(df.columns), reverse=True)
df[list2]

weight  origin                       name   mpg  model_year  horsepower  \
0      3504     usa  chevrolet chevelle malibu  18.0          70       130.0   
1      3693     usa          buick skylark 320  15.0          70       165.0   
2      3436     usa         plymouth satellite  18.0          70       150.0   
3      3433     usa              amc rebel sst  16.0          70       150.0   
4      3449     usa                ford torino  17.0          70       140.0   
..      ...     ...                        ...   ...         ...         ...   
393    2790     usa            ford mustang gl  27.0          82        86.0   
394    2130  europe                  vw pickup  44.0          82        52.0   
395    2295     usa              dodge rampage  32.0          82        84.0   
396    2625     usa                ford ranger  28.0          82        79.0   
397    2720     usa                 chevy s-10  31.0          82        82.0   

     displacement  cylinders  acceleration  
0           307.0          8          12.0  
1           350.0          8          11.5  
2           318.0          8          11.0  
3           304.0          8          12.0  
4           302.0          8          10.5  
..            ...        ...           ...  
393         140.0          4          15.6  
394          97.0          4          24.6  
395         135.0          4          11.6  
396         120.0          4          18.6  
397         119.0          4          19.4  

[398 rows x 9 columns]

In [17]:
# 열분리 : 하나의 열에 들어있는 데이터를 분리하여 개별 변수로 저장
import pandas as pd
df = pd.read_excel('주가데이터.xlsx')
print(df)

          연월일     시가     고가     저가
0  2021-08-01  10850  10900  10000
1  2021-08-02  10550  10900   9990
2  2021-08-03  10900  10950  10150
3  2021-08-04  10800  11050  10500
4  2021-08-05  10900  11000  10700
5  2021-08-06  11400  11450  11000
6  2021-08-07  11250  11450  10750
7  2021-08-08  11350  11750  11200
8  2021-08-09  11200  11600  10900
9  2021-08-10  11850  11950  11300
10 2021-08-11  13400  13400  12000
11 2021-08-12  13600  13600  12900
12 2021-08-13  13200  13700  13150


In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   연월일     13 non-null     datetime64[ns]
 1   시가      13 non-null     int64         
 2   고가      13 non-null     int64         
 3   저가      13 non-null     int64         
dtypes: datetime64[ns](1), int64(3)
memory usage: 544.0 bytes


In [19]:
df['연월일'].astype('str')

0     2021-08-01
1     2021-08-02
2     2021-08-03
3     2021-08-04
4     2021-08-05
5     2021-08-06
6     2021-08-07
7     2021-08-08
8     2021-08-09
9     2021-08-10
10    2021-08-11
11    2021-08-12
12    2021-08-13
Name: 연월일, dtype: object

In [20]:
df['연월일'].astype('str').str.split('-')

0     [2021, 08, 01]
1     [2021, 08, 02]
2     [2021, 08, 03]
3     [2021, 08, 04]
4     [2021, 08, 05]
5     [2021, 08, 06]
6     [2021, 08, 07]
7     [2021, 08, 08]
8     [2021, 08, 09]
9     [2021, 08, 10]
10    [2021, 08, 11]
11    [2021, 08, 12]
12    [2021, 08, 13]
Name: 연월일, dtype: object

In [21]:
df['연']=df['연월일'].astype('str').str.split('-').str.get(0)
df['월']=df['연월일'].astype('str').str.split('-').str.get(1)
df['일']=df['연월일'].astype('str').str.split('-').str.get(2)

In [22]:
print(df)

          연월일     시가     고가     저가     연   월   일
0  2021-08-01  10850  10900  10000  2021  08  01
1  2021-08-02  10550  10900   9990  2021  08  02
2  2021-08-03  10900  10950  10150  2021  08  03
3  2021-08-04  10800  11050  10500  2021  08  04
4  2021-08-05  10900  11000  10700  2021  08  05
5  2021-08-06  11400  11450  11000  2021  08  06
6  2021-08-07  11250  11450  10750  2021  08  07
7  2021-08-08  11350  11750  11200  2021  08  08
8  2021-08-09  11200  11600  10900  2021  08  09
9  2021-08-10  11850  11950  11300  2021  08  10
10 2021-08-11  13400  13400  12000  2021  08  11
11 2021-08-12  13600  13600  12900  2021  08  12
12 2021-08-13  13200  13700  13150  2021  08  13


In [23]:
# 필터링
# 불린 인덱싱 : 조건식에 해당하는 데이터를 판별하여 추출하기 위한 방법
# -> 조건식을 이용하여 각 원소에 대한 불린값 반환 -> 불린값을 T로 데이터만 추출
import seaborn as sns
df = sns.load_dataset('mpg')
print(df['mpg'])

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ... 
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64


In [24]:
mask1 = (df.mpg > 20) & (df.mpg < 30)
df_bool = df.loc[mask1,:]
print(df_bool['mpg'])

14     24.0
15     22.0
17     21.0
18     27.0
19     26.0
       ... 
388    26.0
389    22.0
392    27.0
393    27.0
396    28.0
Name: mpg, Length: 146, dtype: float64


In [25]:
df_bool['mpg'].describe()

count    146.000000
mean      24.807534
std        2.699402
min       20.200000
25%       22.625000
50%       25.000000
75%       27.000000
max       29.900000
Name: mpg, dtype: float64

In [26]:
# 데이터 분석 실습 : 변수변환/재구성/필터링
import seaborn as sns
df = sns.load_dataset('penguins')
print(df)

    species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2     

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [28]:
df.dropna(subset=['body_mass_g','sex'], axis=0, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 333 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            333 non-null    object 
 1   island             333 non-null    object 
 2   bill_length_mm     333 non-null    float64
 3   bill_depth_mm      333 non-null    float64
 4   flipper_length_mm  333 non-null    float64
 5   body_mass_g        333 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 20.8+ KB


In [29]:
# step1. 체중을 3개 군간으로 나누어 집단변수 생성
import numpy as np
np.histogram(df['body_mass_g'], bins=3)

(array([140, 135,  58], dtype=int64), array([2700., 3900., 5100., 6300.]))

In [30]:
count, bin_dividers = np.histogram(df['body_mass_g'], bins=3)
print(bin_dividers)

[2700. 3900. 5100. 6300.]


In [31]:
import pandas as pd
df['bm_bin'] = pd.cut(df['body_mass_g'],
                     bins=bin_dividers,
                     labels=['저체중','보통체중','고체중'],
                     include_lowest=True)
print(df['bm_bin'])

0       저체중
1       저체중
2       저체중
4       저체중
5       저체중
       ... 
338    보통체중
340    보통체중
341     고체중
342     고체중
343     고체중
Name: bm_bin, Length: 333, dtype: category
Categories (3, object): ['저체중' < '보통체중' < '고체중']


In [32]:
# step2 조건에 맞는 새로운 데이터프레임 생성
df.columns

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex', 'bm_bin'],
      dtype='object')

In [36]:
df1 = df[['bm_bin','species','sex','island']]
print(df1)

    bm_bin species     sex     island
0      저체중  Adelie    Male  Torgersen
1      저체중  Adelie  Female  Torgersen
2      저체중  Adelie  Female  Torgersen
4      저체중  Adelie  Female  Torgersen
5      저체중  Adelie    Male  Torgersen
..     ...     ...     ...        ...
338   보통체중  Gentoo  Female     Biscoe
340   보통체중  Gentoo  Female     Biscoe
341    고체중  Gentoo    Male     Biscoe
342    고체중  Gentoo  Female     Biscoe
343    고체중  Gentoo    Male     Biscoe

[333 rows x 4 columns]


In [47]:
# 성별변수를 더미변수로 변환
import pandas as pd
df1['sex'] = pd.get_dummies(df1['sex'], drop_first=True)
df1['sex'] = df1['sex'].replace({1: 0, 0: 1})

print(df1['sex'])

0      0
1      1
2      1
4      1
5      0
      ..
338    1
340    1
341    0
342    1
343    0
Name: sex, Length: 333, dtype: int64


C:\Users\M\.conda\envs\cospropython\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\M\.conda\envs\cospropython\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


In [48]:
# 조건에 맞는 새로운 데이터프레임 생성
mask1 = (df1.sex == 1) & (df1.bm_bin == '고체중')
df1_bool = df1.loc[mask1, :]
print(df1_bool)

    bm_bin species  sex  island
254    고체중  Gentoo    1  Biscoe
293    고체중  Gentoo    1  Biscoe
342    고체중  Gentoo    1  Biscoe
